# Generated by Django 2.1.2 on 2018-10-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181030_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.IntegerField(blank=True, default=0, null=True, verbose_name='Funding')),
                ('has_customers', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('revenue', models.IntegerField(blank=True, default=0, null=True, verbose_name='Revenue')),
                ('fulltime_employees', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fulltime Employees')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='investor',
        ),
        migrations.AddField(
            model_name='stage',
            name='fulltime_employees',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fulltime Employees'),
        ),
        migrations.AddField(
            model_name='stage',
            name='funding',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Funding'),
        ),
        migrations.AddField(
            model_name='stage',
            name='has_customers',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='revenue',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Revenue'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Company'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Investor'),
        ),
        migrations.AddField(
            model_name='companyreport',
            name='product_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ProductStage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='product_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ProductStage'),
        ),
    ]
