# Generated by Django 2.1.2 on 2018-11-01 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181031_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='fulltime_employees',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='has_customers',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='product_stage',
        ),
        migrations.RemoveField(
            model_name='companyreport',
            name='revenue',
        ),
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyreport',
            name='date_updated',
            field=models.DateField(default=datetime.date(2018, 11, 1), verbose_name='Date updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyreport',
            name='stage_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Stage'),
            preserve_default=False,
        ),
    ]
