# Generated by Django 2.1.2 on 2018-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181102_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(default='2018-11-02', max_length=200),
        ),
    ]
