# Generated by Django 2.1.2 on 2018-11-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20181102_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='title',
            new_name='name',
        ),
    ]
