# Generated by Django 2.1.2 on 2018-11-10 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_companystagereport_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystagereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stage_report', to='data.Company'),
        ),
        migrations.AlterField(
            model_name='companystagereport',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 5, 33, 12, 600427), verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='companystagereport',
            name='title',
            field=models.CharField(default='2018-11-10 05:33:12.598945', max_length=200),
        ),
        migrations.AlterField(
            model_name='masterstage',
            name='title',
            field=models.CharField(default='2018-11-10 05:33:12.598945', max_length=200),
        ),
    ]
