# Generated by Django 2.1.2 on 2018-11-10 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20181110_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystagereport',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='companystagereport',
            name='title',
            field=models.CharField(default='<built-in method now of type object at 0x10e18e608>', max_length=200),
        ),
        migrations.AlterField(
            model_name='masterstage',
            name='title',
            field=models.CharField(default='<built-in method now of type object at 0x10e18e608>', max_length=200),
        ),
    ]
