# Generated by Django 2.1.2 on 2018-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20181110_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystagereport',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='masterstage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
