# Generated by Django 2.1.2 on 2018-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20181116_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
