# Generated by Django 2.1.2 on 2018-11-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20181116_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstage',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
